### ISSUE TITLE
report a bug.

### ISSUE THREAD

**Issue by wustwg** [steveliles/Foredroid#11] opened 2017-05-12 01:54 UTC
the old code when it going to "it.remove();",there is a exception ,"java.lang.UnsupportedOperationException" .
The CopyOnWriteArrayList doc describe is “Iterators returned by this list and its sub lists cannot modify the
 * underlying list. In particular, {@link Iterator#remove}, {@link
 * ListIterator#add} and {@link ListIterator#set} all throw {@link
 * UnsupportedOperationException}.”.
It doesn't impliment "remove" method.

This is my solution:
private List<WeakReference<Listener>> listeners = new ArrayList<>();

Please check this issues ,thank you very much for offering so good tool.

**Comment by steveliles** [comment] 2017-07-07 08:17
duplicate of #9 ...

**Closed as completed by steveliles** 2017-07-07 08:17 UTC
